name: Deploy static content to Pages

on:
  # Runs on pushes targeting the default branch
  push:
    branches:
      - master  

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

permissions:
  contents: read
  pages: write

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2  # Menggunakan actions/checkout@v2

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          personal_token: ${{ secrets.GITHUB_TOKEN }}
          external_repository: ikhsanfd1/ikhsan-fd
          publish_dir: . 
